name: Java CI with Maven

on:
  push:
    branches: [ "vp-rem" ]

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Upload Artifact to s3
      working-directory: /home/runner/work/vprofile-project/vprofile-project/target
      run: aws s3 cp *.war s3://artifactstore-814380675453/ROOT.war   

    #- name: Upload the build output
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: vprofile-v2.war
    #    path: |
    #        target/vprofile-v2.war
    #    retention-days: 1

  deploy:
    name: Deploy to EC2
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v3
    #  - name: Download the build output
    #    uses: actions/download-artifact@v2
    #    with:
    #      name: vprofile-v2.war
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      #- name: copy to S3 bucket
      #  run: |
      #    aws s3 cp --region ap-northeast-1 /home/runner/work/vprofile-project/vprofile-project/appspec.yml s3://artifactstore-814380675453/appspec.yml
      #    aws s3 cp --region ap-northeast-1 /home/runner/work/vprofile-project/vprofile-project/vprofile-v2.war s3://artifactstore-814380675453/ROOT.war
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name vprofile-test \
          --deployment-group-name vprofile-app \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
          
      #    --s3-location bucket=artifactstore-814380675453,bundleType=zip,key=vprofile-v2.zip \