# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "vp-rem" ]

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir output
        cp target/vprofile-v2.war output/vprofile-v2.war

    - name: Upload the build output
      uses: actions/upload-artifact@v2
      with:
        name: vprofile-v2.war
        path: |
            output/vprofile-v2.war
        retention-days: 1

  deploy:
    name: Deploy to EC2
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: vprofile-v2.war
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: copy to S3 bucket
        run: |
          aws s3 cp --region ap-northeast-1 /home/runner/work/vprofile-project/vprofile-project/vprofile-v2.war s3://artifactstore-814380675453/vprofile-v2.zip
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name vprofile-test \
          --revision revisionType=s3,s3Location=artifactstore-814380675453,key=vprofile-v2.zip,bundleType=zip \
          --deployment-group-name vprofile-app \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}